config/routes.rb
EmoSearch::Application.routes.draw do
  resources :videos, only: [:index, :show, :create, :update]

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  get 'tags/:tags', to: 'videos#index', as: :tag

  match '/about', to: 'static_pages#about'
  root to: 'static_pages#home'
end
#== Route Map
# Generated on 09 Oct 2012 06:38
#
#                          POST   /videos(.:format)                      videos#create
#                    video GET    /videos/:id(.:format)                  videos#show
#         new_user_session GET    /users/sign_in(.:format)               devise/sessions#new
#             user_session POST   /users/sign_in(.:format)               devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)              devise/sessions#destroy
#  user_omniauth_authorize        /users/auth/:provider(.:format)        omniauth_callbacks#passthru {:provider=>/twitter|facebook/}
#   user_omniauth_callback        /users/auth/:action/callback(.:format) omniauth_callbacks#(?-mix:twitter|facebook)
#            user_password POST   /users/password(.:format)              devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)          devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)         devise/passwords#edit
#                          PUT    /users/password(.:format)              devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                devise/registrations#cancel
#        user_registration POST   /users(.:format)                       devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)               devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                  devise/registrations#edit
#                          PUT    /users(.:format)                       devise/registrations#update
#                          DELETE /users(.:format)                       devise/registrations#destroy
#        user_confirmation POST   /users/confirmation(.:format)          devise/confirmations#create
#    new_user_confirmation GET    /users/confirmation/new(.:format)      devise/confirmations#new
#                          GET    /users/confirmation(.:format)          devise/confirmations#show
#                      tag GET    /tags/:tag(.:format)                   videos#index
#                    about        /about(.:format)                       static_pages#about
#                     root        /                                      static_pages#home

app/models/video.rb
# -*- encoding: utf-8 -*
# == Schema Information
#
# Table name: videos
#
#  id                :integer          not null, primary key
#  nicovideo_id      :string(255)      not null
#  title             :string(255)      not null
#  description       :text             not null
#  thumbnail_url     :string(255)      not null
#  first_retrieve    :datetime         not null
#  length            :string(255)      not null
#  view_counter      :integer          not null
#  comment_num       :integer          not null
#  mylist_counter    :integer          not null
#  watch_url         :string(255)      not null
#  nicovideo_user_id :string(255)      not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

require 'open-uri'

class Video < ActiveRecord::Base
  attr_accessible :comment_num, :description, :first_retrieve, :length, :mylist_counter, :nicovideo_id, :nicovideo_user_id, :thumbnail_url, :title, :view_counter, :watch_url
  attr_accessible :nicovideo_tag_list
  acts_as_taggable_on :nicovideo_tags

  validates :nicovideo_id, presence: true, uniqueness: true
  validates :first_retrieve, presence: true
  validates :thumbnail_url, format: {with: URI::regexp(%w(http https))}
  validates :watch_url, format: {with: URI::regexp(%w(http https))}

  #default_scope order: 'first_retrieve DESC'

  scope :refine_search, lambda { |params|
    composed_scope = self.scoped

    if params[:tags].present?
      params[:tags].split("+").each do |tag|
        composed_scope = composed_scope.tagged_with(tag)
      end
    end

    if params[:range].present?
      case params[:range]
      when "day"
        range = 1.day.ago
      when "week"
        range = 1.week.ago
      when "month"
        range = 1.month.ago
      else
        range = "invalid"
      end
      composed_scope = composed_scope.where("first_retrieve >= ?", range) unless range == "invalid"
    end

    if params[:sort].present?
      case params[:sort]
      when "fd"
        sort_option = "first_retrieve DESC"
      when "fa"
        sort_option = "first_retrieve ASC"
      when "vd"
        sort_option = "view_counter DESC"
      when "va"
        sort_option = "view_counter ASC"
      when "cd"
        sort_option = "comment_num DESC"
      when "ca"
        sort_option = "comment_num ASC"
      when "md"
        sort_option = "mylist_counter DESC"
      when "ma"
        sort_option = "mylist_counter ASC"
      else
        sort_option = "first_retrieve DESC"
      end

      composed_scope = composed_scope.order(sort_option)
    end

    return composed_scope
  }

  # apply nico video attributes when create
  before_validation :apply_attributes, on: :create

  THUMBINFO_BASE_URL = 'http://ext.nicovideo.jp/api/getthumbinfo/'

  def update_attributes
    xml = Nokogiri::XML(open(THUMBINFO_BASE_URL + self.nicovideo_id))
    if nicovideo_api_response_is_valid?(xml) && validate_video_category?(xml)
      self.description = xml.xpath('//description').inner_text
      self.view_counter = xml.xpath('//view_counter').inner_text.to_i
      self.comment_num = xml.xpath('//comment_num').inner_text.to_i
      self.mylist_counter = xml.xpath('//mylist_counter').inner_text.to_i
      # replace "+" to "＋" for tag refine search separater
      self.nicovideo_tag_list = xml.xpath('//tags[contains(@domain, "jp")]//tag').map{|tag| tag.text.gsub("+", "＋") }.join(",")
    else
      return false
    end
  end

  private

  def apply_attributes
    xml = Nokogiri::XML(open(THUMBINFO_BASE_URL + self.nicovideo_id))
    if nicovideo_api_response_is_valid?(xml) && validate_video_category?(xml)
      self.title = xml.xpath('//title').inner_text
      self.description = xml.xpath('//description').inner_text
      self.thumbnail_url = xml.xpath('//thumbnail_url').inner_text
      self.first_retrieve = Time.parse(xml.xpath('//first_retrieve').inner_text)
      self.length = xml.xpath('//length').inner_text
      self.view_counter = xml.xpath('//view_counter').inner_text.to_i
      self.comment_num = xml.xpath('//comment_num').inner_text.to_i
      self.mylist_counter = xml.xpath('//mylist_counter').inner_text.to_i
      self.watch_url = xml.xpath('//watch_url').inner_text
      self.nicovideo_user_id = xml.xpath('//user_id').inner_text
      # replace "+" to "＋" for tag refine search separater
      self.nicovideo_tag_list = xml.xpath('//tags[contains(@domain, "jp")]//tag').map{|tag| tag.text.gsub("+", "＋") }.join(",")
    else
      return false
    end
  end

  def nicovideo_api_response_is_valid?(response_xml)
    if response_xml.at_css('nicovideo_thumb_response')["status"] == "ok"
      return true
    else
      return false
    end
  end

  def validate_video_category?(response_xml)
    tag_list = response_xml.xpath('//tags[contains(@domain, "jp")]//tag').map{|tag| tag.text }.join(",")
    if tag_list.include?("VOCALOID") || tag_list.include?("ニコニコインディーズ")
      return true
    else
      return false
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @videos = Video.refine_search(params).paginate(page: params[:page])
    @tags = Video.refine_search(params).tag_counts_on(:nicovideo_tags)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(nicovideo_id: params[:nicovideo_id])

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { redirect_to videos_path , alert: 'Video was not successfully created.' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])
    @video.update_attributes

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { redirect_to videos_path , alert: 'Video was not successfully updated.' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<div class="well">
  <%= form_tag videos_path, method: :post, class: "form-inline" do %>
    <%= text_field_tag :nicovideo_id , nil, placeholder: "Niconico Video ID", class: "input-medium"%>
    <%= submit_tag "Submit", class: "btn" %>
  <% end %>
</div>

app/views/videos/_search_conditions.html.erb
<div class="well">
  <% if params[:sort] %>
    <span class="label"><%= readable_sort_condition(params[:sort]) %> <%= link_to "x", remove_sort_videos_path, class: "label-close" %></span>
  <% end %>
  <% if params[:range] %>
    <span class="label"><%= readable_range_condition(params[:range]) %> <%= link_to "x", remove_range_videos_path, class: "label-close" %></span>
  <% end %>
  <%= tag "br" if params[:sort].present? || params[:range].present? %>
  <% if params[:tags] %>
    <% params[:tags].split("+").each do |tag| %>
      <span class="label label-info"><%= tag.html_safe %> <%= link_to "x", remove_tag_path(tag), class: "label-close" %></span>
    <% end %>
  <% end %>
</div>

app/views/videos/_side_bar.html.erb
<%= render 'form' if current_user.present? %>
<div class="well">
  <div class="btn-toolbar">
  <div class="btn-group">
    <button class="btn btn-small">表示順</button>
    <button class="btn btn-small dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <!-- dropdown menu links -->
      <li><%= link_to "登録日時が新しい順", sort_videos_path("fd") %></li>
      <li><%= link_to "登録日時が古い順", sort_videos_path("fa") %></li>
      <li><%= link_to "再生数が多い順", sort_videos_path("vd")  %></li>
      <li><%= link_to "再生数が古い順", sort_videos_path("va")  %></li>
      <li><%= link_to "コメント数が多い順", sort_videos_path("cd")  %></li>
      <li><%= link_to "コメント数が少ない順", sort_videos_path("ca")  %></li>
      <li><%= link_to "マイリスト数が多い順", sort_videos_path("md")  %></li>
      <li><%= link_to "マイリスト数が少ない順", sort_videos_path("ma")  %></li>
    </ul>
  </div>
  <div class="btn-group">
    <button class="btn btn-small">投稿日時</button>
    <button class="btn btn-small dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <!-- dropdown menu links -->
      <li><%= link_to "24時間以内", range_scoped_videos_path("day") %></li>
      <li><%= link_to "1週間以内", range_scoped_videos_path("week") %></li>
      <li><%= link_to "1ヶ月以内", range_scoped_videos_path("month") %></li>
    </ul>
  </div>
</div>
  <hr />
  <% tag_cloud(@tags, ["label", "label label-success", "label label-warning", "label label-important"]) do |tag, css_class| %>
    <% if params[:tags].present? && params[:tags].split("+").include?(tag.name) %>
      <span class="label label-info"><%= tag.name.html_safe %></span>
    <% else %>
      <%= link_to tag.name, additional_tag_path(tag.name), class: css_class %>
    <% end %>
  <% end %>
</div>

app/views/videos/_video.html.erb
<div class="row-fluid">
  <div class="span2">
    <%= link_to image_tag(video.thumbnail_url, alt:video.title), video_path(video), class: "thumbnail"%>
  </div>
  <div class="span10">
    <h4><%= link_to video.title.html_safe, video_path(video) %></h4>
    <% video.nicovideo_tags.each do |tag| %>
      <% if params[:tags].present? && params[:tags].split("+").include?(tag.name) %>
        <span class="label label-info"><%= tag.name.html_safe %></span>
      <% else %>
        <%= link_to tag.name.html_safe, tagged_videos_path(tag.name), class: "label" %>
      <% end %>
    <% end %>
    <p>
    <blockquote>
      <%= truncate(video.description, length:150) %>
      <small><%= video.first_retrieve.to_s(:db) %> ( <%= time_ago_in_words video.first_retrieve %> 前に投稿 )</small>
    </blockquote>
    </p>
  </div>
</div><!--/row-->
<hr />

app/views/videos/index.html.erb
<div class="row">
  <div class="span8">
    <div class="page-header">
      <h1>Listing Videos</h1>
    </div>
    <%= render "search_conditions" if params[:sort].present? || params[:range].present? || params[:tags].present? %>
    <%= render @videos %>
    <%= will_paginate @videos %>
  </div>
  <div class="span4">
    <%= render "side_bar" %>
  </div>
</div>

app/views/videos/show.html.erb
<div class="page-header">
  <h1><%= @video.title.html_safe %><small><%= @video.nicovideo_id %></small></h1>
</div>
<div class="row-fluid">
  <div class="span12">
    <% @video.nicovideo_tags.each do |tag| %>
      <%= link_to tag.name.html_safe, tagged_videos_path(tag.name), class: "label" %>
    <% end %>
  </div>
</div>
<div class="row-fluid">
  <div class="span12" align="center">
    <div class="well">
      <%= nico_video_player @video %>
    </div>
  </div>
</div>
<div class="page-header">
  <h2>Information <small>動画情報</small></h2>
</div>
<div class="row-fluid">
  <div class="span2">
    <p align="center"><strong>タイトル</strong></p>
  </div>
  <div class="span10">
    <p><%= link_to @video.title, @video.watch_url, target: "_blank" %></p>
  </div>
</div>
<div class="row-fluid">
  <div class="span2">
    <p align="center"><strong>動画ID</strong></p>
  </div>
  <div class="span10">
    <p><%= link_to @video.nicovideo_id, @video.watch_url, target: "_blank" %></p>
  </div>
</div>
<div class="row-fluid">
  <div class="span2">
    <p align="center"><strong>タグ</strong></p>
  </div>
  <div class="span10">
    <p>
    <% @video.nicovideo_tags.each do |tag| %>
      <%= link_to tag.name, "http://www.nicovideo.jp/tag/#{tag.name}", class: "label", target: "_blank" %>
    <% end %>
    </p>
  </div>
</div>
<div class="row-fluid">
  <div class="span2">
    <p align="center"><strong>説明文</strong></p>
  </div>
  <div class="span10">
    <div class="well">
      <%= @video.description %>
    </div>
  </div>
</div>
<div class="row-fluid">
  <div class="span2">
    <p align="center"><strong>再生時間</strong></p>
  </div>
  <div class="span10">
    <p><%= @video.length %></p>
  </div>
</div>
<div class="row-fluid">
  <div class="span2">
    <p align="center"><strong>カウンター</strong></p>
  </div>
  <div class="span10">
    <p><b>再生数:</b> <%= @video.view_counter %> <b>コメント数:</b> <%= @video.comment_num %> <b>マイリスト登録数:</b> <%= @video.mylist_counter %></p>
  </div>
</div>
<div class="row-fluid">
  <div class="span2">
    <p align="center"><strong>投稿日時</strong></p>
  </div>
  <div class="span10">
    <p><%= @video.first_retrieve.to_s(:db) %> ( <%= time_ago_in_words @video.first_retrieve %> 前に投稿 )</p>
  </div>
</div>
<div class="row-fluid">
  <div class="span2">
    <p align="center"><strong>最終更新日</strong></p>
  </div>
  <div class="span10">
    <p>
    <%= @video.updated_at.to_s(:db) %> ( <%= time_ago_in_words @video.updated_at %> 前に更新 )
    <%= link_to "最新情報に更新", @video, method: :put, class: "btn btn-small btn-info" if current_user.present? %>
    </p>
  </div>
</div>