config/routes.rb
EmoSearch::Application.routes.draw do
  resources :videos, only: [:index, :show, :create, :update]

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  get 'tags/:tags', to: 'videos#index', as: :tag

  match '/about', to: 'static_pages#about'
  root to: 'static_pages#home'
end
#== Route Map
# Generated on 09 Oct 2012 06:38
#
#                          POST   /videos(.:format)                      videos#create
#                    video GET    /videos/:id(.:format)                  videos#show
#         new_user_session GET    /users/sign_in(.:format)               devise/sessions#new
#             user_session POST   /users/sign_in(.:format)               devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)              devise/sessions#destroy
#  user_omniauth_authorize        /users/auth/:provider(.:format)        omniauth_callbacks#passthru {:provider=>/twitter|facebook/}
#   user_omniauth_callback        /users/auth/:action/callback(.:format) omniauth_callbacks#(?-mix:twitter|facebook)
#            user_password POST   /users/password(.:format)              devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)          devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)         devise/passwords#edit
#                          PUT    /users/password(.:format)              devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                devise/registrations#cancel
#        user_registration POST   /users(.:format)                       devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)               devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                  devise/registrations#edit
#                          PUT    /users(.:format)                       devise/registrations#update
#                          DELETE /users(.:format)                       devise/registrations#destroy
#        user_confirmation POST   /users/confirmation(.:format)          devise/confirmations#create
#    new_user_confirmation GET    /users/confirmation/new(.:format)      devise/confirmations#new
#                          GET    /users/confirmation(.:format)          devise/confirmations#show
#                      tag GET    /tags/:tag(.:format)                   videos#index
#                    about        /about(.:format)                       static_pages#about
#                     root        /                                      static_pages#home

app/views/layouts/_flash_message.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, '<a class="close" data-dismiss="alert" href="#">×</a>'.html_safe + value, class: "alert alert-#{key}" %>
<% end %>

app/views/layouts/_footer.html.erb
<hr>
<footer class="footer">
<p>&copy; emo-search 2012</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
<div class="navbar-inner">
  <div class="container">
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    <%= link_to "emo-search", root_path, class: "brand" %>
    <% if user_signed_in? %>
      <div class="btn-group pull-right">
        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-user"></i> <%= current_user.username %> <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", edit_user_registration_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: "delete" %></li>
        </ul>
      </div>
    <% else %>
      <ul class="nav pull-right">
        <li<%= " class='active'".html_safe if current_page?(new_user_registration_path) %>><%= link_to "Sign up", new_user_registration_path %></li>
        <li<%= " class='active'".html_safe if current_page?(new_user_session_path) %>><%= link_to "Sign in", new_user_session_path %></li>
      </ul>
    <% end %>    <div class="nav-collapse collapse">
      <ul class="nav">
        <li<%= ' class="active"'.html_safe if current_page?(root_path) %>><%= link_to "Home", root_path %></li>
        <li<%= ' class="active"'.html_safe if current_page?(videos_path) %>><%= link_to "Videos", videos_path %></li>
        <li<%= ' class="active"'.html_safe if current_page?(about_path) %>><%= link_to "About", about_path %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield :title) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="This is the site which helps you search music by your emotion">
    <meta name="author" content="masay0shi">
    <!-- Le styles -->
    <%= stylesheet_link_tag "application", media: "all" %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= csrf_meta_tags %>
    <%= render 'shared/google_analytics_js' if Rails.env.production? %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/flash_message' if flash.present? %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  </body>
</html>